version: '2.4'
services:
  bot:
    build:
      context: ./
      args:
        FOLDER: ""
    environment:
      TG_API_KEY:  # API key of the bot
      SENTRY_DSN:
      URL_PATH:
      URL_HOSTNAME:
      RABBITMQ_HOST: # "rabbit"
      RABBITMQ_USER: # "rabbit"
      RABBITMQ_PASS: # "1234secure"
      RABBITMQ_VHOST: # app01
      CELERY_WORKER: "no"
      HEALTHCHECK_URL: "/healthcheck"


  worker:
    build:
      context: ./
      args:
        FOLDER: ""
    working_dir: /app/
    restart: "unless-stopped"
    environment:
      TG_API_KEY:  # API key of the bot
      SENTRY_DSN:
      RABBITMQ_HOST: # "rabbit"
      RABBITMQ_USER: # "rabbit"
      RABBITMQ_PASS: # "1234secure"
      RABBITMQ_VHOST: # app01
      CELERY_WORKER: "yes"
    command: "celery worker -A bass_boost.celery.worker --loglevel INFO"
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      # test: ["CMD", "celery", "inspect", "ping", "-A", "tasks.add", "-d", "celery@$HOSTNAME"]

  beat:
    build:
      context: ./
      args:
        FOLDER: ""
    working_dir: /app/
    restart: "unless-stopped"
    environment:
      TG_API_KEY:  # API key of the bot
      SENTRY_DSN:
      RABBITMQ_HOST: # "rabbit"
      RABBITMQ_USER: # "rabbit"
      RABBITMQ_PASS: # "1234secure"
      RABBITMQ_VHOST: # app01
      CELERY_WORKER: "yes"
      HEALTHCHECK_URL: "/test"
    command: "celery beat -A bass_boost.celery.worker --loglevel INFO"
