from .en import Lang as LBase

class Lang(LBase):
    """ Thanks Pigeon """
    lang = "es"
    format_unsupported = "Formato de audio no soportado."
    start_message = "Este bot puede potenciar los graves en archivos de audio. Simplemente envíame un audio."
    help_message = start_message + "\n\nParte de la red de bots de @luckydonaldsbots .\n\nESTE BOT ES TAN MALO\n¡¡¡OYE!!! ¡¡¡TU!!! ¡¡¡POR QUÉ LO USAS?!?"
    caption = "¡@{bot} acaba de potenciar los graves!"
    progress0 = "descargando archivo"
    progress1 = "cargando audio"
    progress2 = "analizando pista de audio"
    progress3 = "calculando el aumento medio de los graves que será necesario"
    progress4 = "calculando potenciación de graves"
    progress5 = "calculando una mayor potenciación de los graves"
    progress6 = "extrayendo regiones para potenciar"
    progress7 = "aplicando potenciación de graves a la pista de audio original"
    capslock_number_1 = "UNO"
    capslock_number_11 = "ONCE"
    capslock_number_111 = "CIENTOONCE"
    generic_error = "Ha ocurrido un error. Por favor inténtalo de nuevo cuando el bug se haya corregido."
    task_scheduled = "Tu pista de audio se ha añadido a la cola de aumento de graves."